src/objects/QwikScore_Question__c.object
<CustomObject>
    <description>A question to ask.</description>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>What type of question is this? Only numeric questions will count toward the final scoring result.</description>
        <inlineHelpText>What type of question is this? Only numeric questions will count toward the final scoring result.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Numeric</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QwikScore_Question_Group__c</fullName>
        <description>Which question group does this question belong to?</description>
        <inlineHelpText>Which question group does this question belong to?</inlineHelpText>
        <label>Group</label>
        <referenceTo>QwikScore_Question_Group__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>QwikScore_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>QQ-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Question_Answer__c.object
<CustomObject>
    <description>Answers to questions in a survey.</description>
    <fields>
        <fullName>IsAnswered__c</fullName>
        <description>Displays 0 if the question has not been answered. Displays 1 if it has been.</description>
        <formula>IF(ISNULL( Answer_Text__c ), 0, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays 0 if the question has not been answered. Displays 1 if it has been.</inlineHelpText>
        <label>IsAnswered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Which question is this an answer for?</description>
        <inlineHelpText>Which question is this an answer for?</inlineHelpText>
        <label>Question</label>
        <referenceTo>QwikScore_Question__c</referenceTo>
        <relationshipLabel>Question Answers</relationshipLabel>
        <relationshipName>QwikScore_Question_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QwikScore_Scorecard__c</fullName>
        <description>Which scorecard does this question answer belong to?</description>
        <inlineHelpText>Which scorecard does this question answer belong to?</inlineHelpText>
        <label>Scorecard</label>
        <referenceTo>QwikScore_Scorecard__c</referenceTo>
        <relationshipLabel>Question Answers</relationshipLabel>
        <relationshipName>QwikScore_Question_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weighted_Score__c</fullName>
        <description>The weighted score of this answer</description>
        <formula>(Answer_Value__c /  Question__r.Maximum_Value__c ) *  Question__r.Question_Weight__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The weighted score of this answer</inlineHelpText>
        <label>Weighted Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Question Answer</label>
    <nameField>
        <displayFormat>QQA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Question_Group__c.object
<CustomObject>
    <description>Groups of questions</description>
    <fields>
        <fullName>Group_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <description>How much of the overall score is this group worth</description>
        <inlineHelpText>How much of the overall score is this group worth</inlineHelpText>
        <label>Group Weight</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Question Group</label>
    <nameField>
        <label>Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Scorecard__c.object
<CustomObject>
    <description>A record of question answers for a survey.</description>
    <fields>
        <fullName>Final_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What is the final score of this survey score card?</description>
        <inlineHelpText>What is the final score of this survey score card?</inlineHelpText>
        <label>Final Score</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Scored__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has the survey been scored and locked?</description>
        <inlineHelpText>Has the survey been scored and locked?</inlineHelpText>
        <label>Scored</label>
        <type>Checkbox</type>
    </fields>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>QSS-{000000}</displayFormat>
        <label>Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

deploy_packages/cs2072/classes/ScoringEngineLite.cls
/***************************************************************************
 Name : ScoringEngine
 Created By : Kyle Bowerman (kbowerman@appirio.com)
    modified from Jeff Douglas' cloudspokes class ScoringEngine
 Created Date :6/28/2012
 Description : Performs total score calculation
 https://docs.google.com/a/appirio.com/document/d/1FsFAD-oJ-oW6xxtH7Au-ekfmvAyi8jWuI55a89KmhXQ/edit
 for more info. Test class is Test_ScorecardEngine. 
 Appirio Inc all rights reserved        
***************************************************************************/

public with sharing class ScoringEngineLite {

 /**
  * Grade an individual scorecard. Never in bulk.
  */
  public static void gradeScorecard(Id scorecardId) {
   
   // QwikScore_Scorecard__c sc = [select Id, Reviewer__r.name, username__c, challenge_participant__r.challenge__c from QwikScore_Scorecard__c where id = :scorecardId];
     QwikScore_Scorecard__c sc = [select Id  from QwikScore_Scorecard__c where id = :scorecardId];
   
   
    // add the info to chatter
    //Utils.addChallengeChatterTextPost(sc.challenge_participant__r.challenge__c, 'Grading scorecard for '+sc.username__c);
   
      try {
     
      //To grade a score card, we need to find all answers associated with it, take their weighted scores and sum them.
      //then multiple that total by the group weight.
      decimal totalWeightedScore = 0.0;
      decimal maxScore = 0.0;
     
      if(maxScore == null)
        maxScore = 0; 
     
      //ok now run an aggregate query that sums all the weighted question answers, but breaks them
      //down by the group so we can multile each total by it's group weight. 
      AggregateResult[] answers = [ select SUM(Weighted_Score__c)totalScore, Question__r.QwikScore_Question_Group__c,
        max(Question__r.QwikScore_Question_Group__r.Group_Weight__c)groupWeight
        from QwikScore_Question_Answer__c
        where IsAnswered__c = 1 and
        Question__r.Question_Type__c = 'Numeric' and
        QwikScore_Scorecard__c = :scorecardId
        Group by ROLLUP(Question__r.QwikScore_Question_Group__c)];
        System.Debug('ktb answers Size: '+ answers.Size());
     
     
      //loop over the groups. There is 1 row for each group (+1 for a grand total row that we ignore)             
      for(AggregateResult ar: answers) {
        //An aggreate query contains a summary row at the end with the totals. Since we don't want to include
        //that in our math, add this if statment to exclude it, since it doesn't have a question group.
        if(ar.get('QwikScore_Question_Group__c') != null) {
  
          string questionGroup = (string) ar.get('QwikScore_Question_Group__c');
  
          decimal thisGroupWeight = (decimal)ar.get('groupWeight') / 100;
          decimal thisWeightedScore = (decimal)ar.get('totalScore');
          decimal thisWeightedTotal = (thisWeightedScore * thisGroupWeight);
         
          totalWeightedScore += thisWeightedTotal;
 
        }                               
      }
     
      totalWeightedScore = (totalWeightedScore)*100;
     
      //update the existing scorecard object with the new total weight and set the
      //scored checkmark to true so the user cannot modify their answers any more.
      QwikScore_Scorecard__c thisScoreCard = [select id, createdbyid from QwikScore_Scorecard__c where id = :scorecardId];
      thisScoreCard.Final_Score__c =  totalWeightedScore;
      thisScoreCard.Scored__c = true;
      System.Debug('ktb TotalWeigtedScore: '+ totalWeightedScore);
       System.Debug('ktb scorecardId:'+ scorecardId);
      
      update thisScoreCard;
           
    } catch(Exception e) {
     // Logger.log(Logger.FATAL, 'ScoringEngine', 'Error scoring scorecard '+ scorecardId + '. Error: '+e.getMessage());
     System.Debug('Fatal ScoringEngine Error scoring scorecard '+ scorecardId + '. Error: '+e.getMessage());
    } 
    } 
   
  }