deploy_packages/cs2072/objects/QwikScore__c.object
<CustomObject>
    <description>Object to hold main types of scorecards.</description>
    <label>Scorecard Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scorecard Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QwikScore_Question__c.object
<CustomObject>
    <description>A question to ask.</description>
    <fields>
        <fullName>Maximum_Value__c</fullName>
        <defaultValue>4</defaultValue>
        <description>What is the maximum value for this question (numeric questions only)</description>
        <inlineHelpText>What is the maximum value for this question (numeric questions only)</inlineHelpText>
        <label>Maximum Value</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Value__c</fullName>
        <defaultValue>1</defaultValue>
        <description>What is the lowest value (if this is a numeric type question)</description>
        <inlineHelpText>What is the lowest value (if this is a numeric type question)</inlineHelpText>
        <label>Minimum Value</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <description>The question to be presented to the user.</description>
        <inlineHelpText>The question to be presented to the user.</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QwikScore_Question_Group__c</fullName>
        <description>Which question group does this question belong to?</description>
        <inlineHelpText>Which question group does this question belong to?</inlineHelpText>
        <label>Group</label>
        <referenceTo>QwikScore_Question_Group__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>QwikScore_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>QQ-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Question_Answer__c.object
<CustomObject>
    <description>Answers to questions in a survey.</description>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <description>What is the text value of the answer given to this question.</description>
        <inlineHelpText>What is the text value of the answer given to this question.</inlineHelpText>
        <label>Answer Text</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionGroupId__c</fullName>
        <formula>Question__r.QwikScore_Question_Group__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QuestionGroupId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Which question is this an answer for?</description>
        <inlineHelpText>Which question is this an answer for?</inlineHelpText>
        <label>Question</label>
        <referenceTo>QwikScore_Question__c</referenceTo>
        <relationshipLabel>Question Answers</relationshipLabel>
        <relationshipName>QwikScore_Question_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QwikScore_Scorecard__c</fullName>
        <description>Which scorecard does this question answer belong to?</description>
        <inlineHelpText>Which scorecard does this question answer belong to?</inlineHelpText>
        <label>Scorecard</label>
        <referenceTo>QwikScore_Scorecard__c</referenceTo>
        <relationshipLabel>Question Answers</relationshipLabel>
        <relationshipName>QwikScore_Question_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Answer</label>
    <nameField>
        <displayFormat>QQA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Question_Group__c.object
<CustomObject>
    <description>Groups of questions</description>
    <fields>
        <fullName>QwikScore_Survey__c</fullName>
        <description>Which scorecard does this question group belong to?</description>
        <inlineHelpText>Which scorecard does this question group belong to?</inlineHelpText>
        <label>Scorecard</label>
        <referenceTo>QwikScore__c</referenceTo>
        <relationshipLabel>Question Groups</relationshipLabel>
        <relationshipName>QwikScore_Question_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Group</label>
    <nameField>
        <label>Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Scorecard__c.object
<CustomObject>
    <description>A record of question answers for a survey.</description>
    <fields>
        <fullName>Final_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What is the final score of this survey score card?</description>
        <inlineHelpText>What is the final score of this survey score card?</inlineHelpText>
        <label>Final Score</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>QwikScore_Survey__c</fullName>
        <description>Which survey is this scorecard related to?</description>
        <inlineHelpText>Which survey is this scorecard related to?</inlineHelpText>
        <label>Survey</label>
        <referenceTo>QwikScore__c</referenceTo>
        <relationshipLabel>Scorecards</relationshipLabel>
        <relationshipName>QwikScore_Scorecard</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_For__c</fullName>
        <label>Survey For</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scorecard</relationshipLabel>
        <relationshipName>Scorecard</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Raw_Score__c</fullName>
        <description>The total raw score of all related questions.</description>
        <inlineHelpText>The total raw score of all related questions.</inlineHelpText>
        <label>Total Raw Score</label>
        <summarizedField>QwikScore_Question_Answer__c.Answer_Value__c</summarizedField>
        <summaryFilterItems>
            <field>QwikScore_Question_Answer__c.IsAnswered__c</field>
            <operation>equals</operation>
            <value>1</value>
        </summaryFilterItems>
        <summaryForeignKey>QwikScore_Question_Answer__c.QwikScore_Scorecard__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>QSS-{000000}</displayFormat>
        <label>Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveyResultsController.cls
public with sharing class SurveyResultsController {
    public Account surveyAccount{get;set;}
    public User surveyUser{get;set;}
    public QwikScore__c scoreCardType{get;set;}
    public QwikScore_Scorecard__c scoreCard{get;set;}
    public List<QwikScore_Question_Group__c> questionGroups{get;set;}
    public map<Id,List<QwikScore_Question_Answer__c>> questionAnswerMap{get;set;}
    public Boolean isValid{get;set;}
    //Constructor
    public SurveyResultsController(){
        questionAnswerMap = new map<Id,List<QwikScore_Question_Answer__c>>();
        questionGroups = new List<QwikScore_Question_Group__c>();
        isValid=false;
        String scoreCardId = ApexPages.currentPage().getParameters().get('score_card_id');
        fillScoreCard(scoreCardId);
        fillScoreCardType();
    }
    //Filling Score card object
    public void fillScoreCard(String scoreCardId){
        scoreCard = [SELECT Id,Name,Survey_For__c,Survey_For__r.Name, 
        							 Total_Raw_Score__c, Final_Score__c,
                       CreatedBy.Name,CreatedDate,  QwikScore_Survey__c,QwikScore_Survey__r.Name 
                     FROM QwikScore_Scorecard__c 
                     WHERE Id = :scoreCardId];
    }
    
   
    //Filling ScoreCard Type object
    public void fillScoreCardType(){
        //Geting the ScoreCard Type record with question Groups
        scoreCardType = [SELECT Id,Name, 
                           (SELECT Id,Name 
                            FROM QwikScore_Question_Groups__r)
                         FROM QwikScore__c 
                         WHERE Id = :scoreCard.QwikScore_Survey__c];
        set<Id> qGroupIdSet = new set<Id>();
        questionGroups.addAll(scoreCardType.QwikScore_Question_Groups__r);
        for(QwikScore_Question_Group__c qGroup:scoreCardType.QwikScore_Question_Groups__r){
            qGroupIdSet.add(qGroup.Id);
        }
        //Creating a map of question group and question answer record
        for(QwikScore_Question_Answer__c questionAns:[SELECT Id,Name,Answer_Text__c,QuestionGroupId__c ,Question__r.Question_Text__c, 
                                                                                             Question__r.Maximum_Value__c,Question__r.Minimum_Value__c
                                                                                FROM QwikScore_Question_Answer__c 
                                                                                WHERE QwikScore_Scorecard__c 
                                                                                = : scoreCard.Id]){
            if(!questionAnswerMap.containsKey(questionAns.QuestionGroupId__c)){
                questionAnswerMap.put(questionAns.QuestionGroupId__c,new List<QwikScore_Question_Answer__c>());
            }
            questionAnswerMap.get(questionAns.QuestionGroupId__c).add(questionAns);
        }
    }
    
    
    public PageReference cancel(){
        return new PageReference('/'+scoreCard.Id);
    }
}