deploy_packages/cs2072/objects/QwikScore__c.object
<CustomObject>
    <description>Object to hold main types of scorecards.</description>
    <label>Scorecard Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scorecard Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QwikScore_Question__c.object
<CustomObject>
    <description>A question to ask.</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Maximum_Value__c</fullName>
        <defaultValue>4</defaultValue>
        <description>What is the maximum value for this question (numeric questions only)</description>
        <inlineHelpText>What is the maximum value for this question (numeric questions only)</inlineHelpText>
        <label>Maximum Value</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Value__c</fullName>
        <defaultValue>1</defaultValue>
        <description>What is the lowest value (if this is a numeric type question)</description>
        <inlineHelpText>What is the lowest value (if this is a numeric type question)</inlineHelpText>
        <label>Minimum Value</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <description>The question to be presented to the user.</description>
        <inlineHelpText>The question to be presented to the user.</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>What type of question is this? Only numeric questions will count toward the final scoring result.</description>
        <inlineHelpText>What type of question is this? Only numeric questions will count toward the final scoring result.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Numeric</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <description>How much of this questions group total score is this question worth (0 - 100)</description>
        <inlineHelpText>How much of this questions group total score is this question worth (0 - 100)</inlineHelpText>
        <label>Weight</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>QwikScore_Question_Group__c</fullName>
        <description>Which question group does this question belong to?</description>
        <inlineHelpText>Which question group does this question belong to?</inlineHelpText>
        <label>Group</label>
        <referenceTo>QwikScore_Question_Group__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>QwikScore_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <defaultValue>1</defaultValue>
        <description>In what order should this question be presented within it&apos;s group? Lower numbers come first.</description>
        <inlineHelpText>In what order should this question be presented within it&apos;s group? Lower numbers come first.</inlineHelpText>
        <label>Sequence Number</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>QQ-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Question_Answer__c.object
<CustomObject>
    <description>Answers to questions in a survey.</description>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <description>What is the text value of the answer given to this question.</description>
        <inlineHelpText>What is the text value of the answer given to this question.</inlineHelpText>
        <label>Answer Text</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Answer_Unique_Id__c</fullName>
        <description>A unique identifier to make sure the same question is not answered more than once for a single scorecard.</description>
        <inlineHelpText>A unique identifier to make sure the same question is not answered more than once for a single scorecard.</inlineHelpText>
        <label>Answer Unique Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Which question is this an answer for?</description>
        <inlineHelpText>Which question is this an answer for?</inlineHelpText>
        <label>Question</label>
        <referenceTo>QwikScore_Question__c</referenceTo>
        <relationshipLabel>Question Answers</relationshipLabel>
        <relationshipName>QwikScore_Question_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QwikScore_Scorecard__c</fullName>
        <description>Which scorecard does this question answer belong to?</description>
        <inlineHelpText>Which scorecard does this question answer belong to?</inlineHelpText>
        <label>Scorecard</label>
        <referenceTo>QwikScore_Scorecard__c</referenceTo>
        <relationshipLabel>Question Answers</relationshipLabel>
        <relationshipName>QwikScore_Question_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Answer</label>
    <nameField>
        <displayFormat>QQA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Question_Group__c.object
<CustomObject>
    <description>Groups of questions</description>
    <fields>
        <fullName>Group_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <description>How much of the overall score is this group worth</description>
        <inlineHelpText>How much of the overall score is this group worth</inlineHelpText>
        <label>Group Weight</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>QwikScore_Survey__c</fullName>
        <description>Which scorecard does this question group belong to?</description>
        <inlineHelpText>Which scorecard does this question group belong to?</inlineHelpText>
        <label>Scorecard</label>
        <referenceTo>QwikScore__c</referenceTo>
        <relationshipLabel>Question Groups</relationshipLabel>
        <relationshipName>QwikScore_Question_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Controls the ordering of question groups when presented to a user.</description>
        <inlineHelpText>In what order should this group be displayed? Lower numbers come first.</inlineHelpText>
        <label>Sequence Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question Group</label>
    <nameField>
        <label>Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Scorecard__c.object
<CustomObject>
    <description>A record of question answers for a survey.</description>
    <fields>
        <fullName>Final_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What is the final score of this survey score card?</description>
        <inlineHelpText>What is the final score of this survey score card?</inlineHelpText>
        <label>Final Score</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>QwikScore_Survey__c</fullName>
        <description>Which survey is this scorecard related to?</description>
        <inlineHelpText>Which survey is this scorecard related to?</inlineHelpText>
        <label>Survey</label>
        <referenceTo>QwikScore__c</referenceTo>
        <relationshipLabel>Scorecards</relationshipLabel>
        <relationshipName>QwikScore_Scorecard</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_For__c</fullName>
        <label>Survey For</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scorecard</relationshipLabel>
        <relationshipName>Scorecard</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>QSS-{000000}</displayFormat>
        <label>Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveyMobileController.cls
/*
 * Controller for the mobile-optimized survey page (SurveyMobil.page)
 *
 * 07/10/2012  Cory McIlroy added header to this class.  also added call to ScoringEngineLite after save.  other minor changes
 * 02/26/2013 Moved from SurveyMobileControllerTalesforce to SurveyMobileControllerT
 */
public with sharing class SurveyMobileController {
    
     /* Getter method for attachment URL */
    public string AttachementUrl{
        get{
            return getSfInstance()+'/apex/AttachmentUpload?aid='+ApexPages.currentPage().getParameters().get('aid')+'&stid='+ApexPages.currentPage().getParameters().get('stid');
        }
    }
    
    //constructor
    public SurveyMobileController(){
    	//constructor element.
    }
    /* Get Salesforce Instance */
    public String getSfInstance()
    {
          return URL.getSalesforceBaseUrl().toExternalForm();
    }
       
    /* Old code from Cory McIlroy starts here */
    
    public static Account surveyAccount;
    public static QwikScore__c scoreCardType;

   
    @RemoteAction 
        public static QwikScore_Scorecard__c saveScoreCard(String jsonString){
            List<QwikScore_Question_Answer__c> answerList = (List<QwikScore_Question_Answer__c>)JSON.deserialize(jsonString, List<QwikScore_Question_Answer__c>.class);
            QwikScore_Scorecard__c scoreCard = new QwikScore_Scorecard__c();
            if (answerList.size() > 0){
                scoreCard = answerList[0].QwikScore_Scorecard__r;
                insert scoreCard;
                for(QwikScore_Question_Answer__c answer: answerList){
                    answer.QwikScore_Scorecard__r = null;
                    answer.QwikScore_Scorecard__c = scoreCard.id;                    
                    answer.Answer_Unique_Id__c = String.valueOf(Math.random());
                }
                insert answerList;

                //Call the scoring package
                ScoringEngineLite.gradeScorecard(scoreCard.Id);  //ktb 7.2

                surveyAccount = getAccountInfo(scoreCard.Survey_For__c);
                scoreCardType = getScoreCardType(scoreCard.QwikScore_Survey__c);

                    
                if (surveyAccount != null && scoreCardType != null) {
                 /* cleaned up a lot of unused code from here */
                        List<QwikScore_Scorecard__c> finishedScoreCards = 
                            [select Final_Score__c from QwikScore_Scorecard__c 
                            where QwikScore_Survey__c = :scoreCardType.Id 
                            and Survey_For__c = :surveyAccount.Id 
                            order by createdDate desc limit 10];
                        Decimal totalScore = 0.0;
                        for(QwikScore_Scorecard__c sCard:finishedScoreCards){
                            totalScore += sCard.Final_Score__c;
                      // once done calculating total score, update the survey account
                        update surveyAccount;
                    }
                }
                else {
                    //TODO
                    System.debug('survey and/or scorecardtype should not be null');
                }
            }
            
            //upload image as attachment.            
            return scoreCard;
        }

    //Method to create a list of question answers for the given score card type
    @RemoteAction 
        public static List<QwikScore_Question_Answer__c> questionAnswersJS(String accountId, String scoreCardTypeId){
            List<QwikScore_Question_Answer__c> questionAnswers = new List<QwikScore_Question_Answer__c>();
            QwikScore_Scorecard__c qs = new QwikScore_Scorecard__c();
            surveyAccount = getAccountInfo(accountId);
            scoreCardType = getScoreCardType(scoreCardTypeId);
            if (surveyAccount == null || scoreCardType == null) {
                return null;
            }
                    if(!checkSurveyAccessibility(scoreCardType)){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Sorry! '+scoreCardType.Name+' survey is not available'));
                        return null;
                    }
            qs.Survey_For__c = surveyAccount.Id;
            qs.Survey_For__r = surveyAccount;
            qs.QwikScore_Survey__c = scoreCardType.Id;
            qs.QwikScore_Survey__r = scoreCardType;
            //Geting the ScoreCard Type record with question Groups
            List<QwikScore_Question_Group__c> listOfGroups = [SELECT Id FROM QwikScore_Question_Group__c WHERE QwikScore_Survey__c = :scoreCardTypeId];
            //Creating a map of question group and question answer record
            QwikScore_Question_Answer__c qAnswer = null; 
            for(QwikScore_Question__c question:[SELECT Id,Name,QwikScore_Question_Group__c, 
                    QwikScore_Question_Group__r.Sequence_Number__c,
                    QwikScore_Question_Group__r.Group_Weight__c,
                    QwikScore_Question_Group__r.Name,
                    QwikScore_Question_Group__r.QwikScore_Survey__c,
                    QwikScore_Question_Group__r.QwikScore_Survey__r.Name,
                    Sequence_Number__c,
                    Question_Text__c,
                    Maximum_Value__c,
                    Minimum_Value__c,
                    Question_Type__c,
                    IsHidden__c,unhideIfQuestion__c,unhideQuestionValue__c,
                    Question_Weight__c,
                    State__c,
                    Area__c
                    FROM QwikScore_Question__c 
                    WHERE QwikScore_Question_Group__c 
                    IN : listOfGroups
                    ORDER BY QwikScore_Question_Group__r.Sequence_Number__c, Sequence_Number__c]){
                qAnswer = new QwikScore_Question_Answer__c();
                qAnswer.Question__c = question.Id;
                qAnswer.Question__r = question;
                qAnswer.Answer_Text__c = null;
                qAnswer.comments__c= null;
                qAnswer.QwikScore_Scorecard__r  = qs;
                questionAnswers.add(qAnswer);
            }
            //put here for testing, commenting out - system.assert(false, questionAnswers);
            System.debug(questionAnswers);
            return questionAnswers;
        } 
    
    public static Account getAccountInfo(String accountId){
        List<Account> accounts = [SELECT Id,Name,BillingStreet, BillingState, BillingPostalCode,
            BillingCountry, BillingCity from Account where Id = :accountId];
        if (accounts != null && accounts.size()>0) {
            return accounts[0];
        }
        else {
            return null;
        }
    }
    public static QwikScore__c getScoreCardType(String scoreCardTypeId){
        List<QwikScore__c> scoreCardTypes = [SELECT Id,Name FROM QwikScore__c WHERE Id = :scoreCardTypeId];
        if (scoreCardTypes != null && scoreCardTypes.size()>0) {
            return scoreCardTypes[0];
        }
        else {
            return null;
        }
    }
        public static Boolean checkSurveyAccessibility(QwikScore__c surveyType){
        if(UserInfo.getName() == 'surveys Site Guest User' && surveyType.Name != 'Customer Satisfaction'){
            return false;
        }
        else{
            return true;
        }
    }    
}