deploy_packages/cs2072/objects/QwikScore__c.object
<CustomObject>
    <description>Object to hold main types of scorecards.</description>
    <label>Scorecard Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scorecard Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QwikScore_Question__c.object
<CustomObject>
    <description>A question to ask.</description>
    <fields>
        <fullName>Maximum_Value__c</fullName>
        <defaultValue>4</defaultValue>
        <description>What is the maximum value for this question (numeric questions only)</description>
        <inlineHelpText>What is the maximum value for this question (numeric questions only)</inlineHelpText>
        <label>Maximum Value</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum_Value__c</fullName>
        <defaultValue>1</defaultValue>
        <description>What is the lowest value (if this is a numeric type question)</description>
        <inlineHelpText>What is the lowest value (if this is a numeric type question)</inlineHelpText>
        <label>Minimum Value</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <description>The question to be presented to the user.</description>
        <inlineHelpText>The question to be presented to the user.</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>What type of question is this? Only numeric questions will count toward the final scoring result.</description>
        <inlineHelpText>What type of question is this? Only numeric questions will count toward the final scoring result.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Numeric</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QwikScore_Question_Group__c</fullName>
        <description>Which question group does this question belong to?</description>
        <inlineHelpText>Which question group does this question belong to?</inlineHelpText>
        <label>Group</label>
        <referenceTo>QwikScore_Question_Group__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>QwikScore_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <defaultValue>1</defaultValue>
        <description>In what order should this question be presented within it&apos;s group? Lower numbers come first.</description>
        <inlineHelpText>In what order should this question be presented within it&apos;s group? Lower numbers come first.</inlineHelpText>
        <label>Sequence Number</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>QQ-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Question_Answer__c.object
<CustomObject>
    <description>Answers to questions in a survey.</description>
    <fields>
        <fullName>Answer_Unique_Id__c</fullName>
        <description>A unique identifier to make sure the same question is not answered more than once for a single scorecard.</description>
        <inlineHelpText>A unique identifier to make sure the same question is not answered more than once for a single scorecard.</inlineHelpText>
        <label>Answer Unique Id</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Which question is this an answer for?</description>
        <inlineHelpText>Which question is this an answer for?</inlineHelpText>
        <label>Question</label>
        <referenceTo>QwikScore_Question__c</referenceTo>
        <relationshipLabel>Question Answers</relationshipLabel>
        <relationshipName>QwikScore_Question_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QwikScore_Scorecard__c</fullName>
        <description>Which scorecard does this question answer belong to?</description>
        <inlineHelpText>Which scorecard does this question answer belong to?</inlineHelpText>
        <label>Scorecard</label>
        <referenceTo>QwikScore_Scorecard__c</referenceTo>
        <relationshipLabel>Question Answers</relationshipLabel>
        <relationshipName>QwikScore_Question_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Answer</label>
    <nameField>
        <displayFormat>QQA-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Question_Group__c.object
<CustomObject>
    <description>Groups of questions</description>
    <fields>
        <fullName>QwikScore_Survey__c</fullName>
        <description>Which scorecard does this question group belong to?</description>
        <inlineHelpText>Which scorecard does this question group belong to?</inlineHelpText>
        <label>Scorecard</label>
        <referenceTo>QwikScore__c</referenceTo>
        <relationshipLabel>Question Groups</relationshipLabel>
        <relationshipName>QwikScore_Question_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Controls the ordering of question groups when presented to a user.</description>
        <inlineHelpText>In what order should this group be displayed? Lower numbers come first.</inlineHelpText>
        <label>Sequence Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question Group</label>
    <nameField>
        <label>Question Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QwikScore_Scorecard__c.object
<CustomObject>
    <description>A record of question answers for a survey.</description>
    <fields>
        <fullName>Final_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What is the final score of this survey score card?</description>
        <inlineHelpText>What is the final score of this survey score card?</inlineHelpText>
        <label>Final Score</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>QwikScore_Survey__c</fullName>
        <description>Which survey is this scorecard related to?</description>
        <inlineHelpText>Which survey is this scorecard related to?</inlineHelpText>
        <label>Survey</label>
        <referenceTo>QwikScore__c</referenceTo>
        <relationshipLabel>Scorecards</relationshipLabel>
        <relationshipName>QwikScore_Scorecard</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey_For__c</fullName>
        <label>Survey For</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scorecard</relationshipLabel>
        <relationshipName>Scorecard</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>QSS-{000000}</displayFormat>
        <label>Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveyController.cls
/*
 * Controller for the original Survey, probably deprecated in favor of the mobile one?
 */
public with sharing class SurveyController {
    public Account surveyAccount{get;set;}
    public User surveyUser{get;set;}
    public QwikScore__c scoreCardType{get;set;}
    public QwikScore_Scorecard__c scoreCard{get;set;}
    public List<QwikScore_Question_Group__c> questionGroups{get;set;}
    public map<Id,List<QwikScore_Question_Answer__c>> questionAnswerMap{get;set;}
    public Boolean isValid{get;set;}
        public map<Integer,List<SelectOption>> answerValues{get;set;}
    //Constructor
    public SurveyController(){
        isValid=false;
        String accountId = ApexPages.currentPage().getParameters().get('account_id');
        String userId = ApexPages.currentPage().getParameters().get('user_id');
        String scoreCardTypeId = ApexPages.currentPage().getParameters().get('scorecard_type_id');
        questionAnswerMap = new map<Id,List<QwikScore_Question_Answer__c>>();
        questionGroups = new List<QwikScore_Question_Group__c>();
        answerValues = new map<Integer,List<SelectOption>>(); 
        if(surveyAccount==null){
            if(accountId!=null){
                fillAccount(accountId);
            }
            else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Account Id is not available'));
            }
        }
        if(surveyUser==null){
            if(userId!=null){
                fillUser(userId);
            }
            else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'User Id is not available'));
            }
        }
        if(scoreCardType==null && (!ApexPages.hasMessages())){
            if(scoreCardTypeId!=null){
                fillScoreCardType(scoreCardTypeId);
                isValid = true;
                scoreCard = new QwikScore_Scorecard__c();
                scoreCard.Survey_For__c = surveyAccount.Id;
                scoreCard.QwikScore_Survey__c = scoreCardType.Id;
            }
            else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'ScoreCard Type Id is not available'));
            }
            
        }
    }
    //Filling Account object 
    public void fillAccount(String accountId){
        surveyAccount = [SELECT Id,Name FROM Account WHERE Id = :accountId];
    }
    //Filling User object
    public void fillUser(String userId){
        surveyUser = [SELECT Id,Name FROM User WHERE Id = :userId];
        
    }
    //Filling ScoreCard Type object
    public void fillScoreCardType(String scoreCardTypeId){
        //Geting the ScoreCard Type record with question Groups
        scoreCardType = [SELECT Id,Name, 
                           (SELECT Id,Name 
                            FROM QwikScore_Question_Groups__r order by Sequence_Number__c)
                         FROM QwikScore__c 
                         WHERE Id = :scoreCardTypeId];
        set<Id> qGroupIdSet = new set<Id>();
        questionGroups.addAll(scoreCardType.QwikScore_Question_Groups__r);
        for(QwikScore_Question_Group__c qGroup:scoreCardType.QwikScore_Question_Groups__r){
            qGroupIdSet.add(qGroup.Id);
        }
        //Creating a map of question group and question answer record
        QwikScore_Question_Answer__c qAnswer = null; 
        for(QwikScore_Question__c question:[SELECT Id,Name,QwikScore_Question_Group__c,Question_Text__c, 
                                            	Question_Type__c,Maximum_Value__c,Minimum_Value__c
                                            FROM QwikScore_Question__c 
                                            WHERE QwikScore_Question_Group__c 
                                            IN : qGroupIdSet order by Sequence_Number__c]){
            if(!questionAnswerMap.containsKey(question.QwikScore_Question_Group__c)){
                questionAnswerMap.put(question.QwikScore_Question_Group__c,new List<QwikScore_Question_Answer__c>());
            }
            if(!answerValues.containsKey(Integer.valueOf(question.Maximum_Value__c))){
                fillAnswerValues(Integer.valueOf(question.Minimum_Value__c),Integer.valueOf(question.Maximum_Value__c));
            }
            qAnswer = new QwikScore_Question_Answer__c();
            qAnswer.Question__c = question.Id;
            qAnswer.Question__r = question;
//          qAnswer.QwikScore_Scorecard__c = scoreCard.Id;
            questionAnswerMap.get(question.QwikScore_Question_Group__c).add(qAnswer);
        }
    }
    public PageReference save(){
        //saving the score card first
        insert scoreCard;
        List<QwikScore_Question_Answer__c> toSaveList = new List<QwikScore_Question_Answer__c>();
        //creating a single list of question answers of different group
        for(QwikScore_Question_Group__c qGroup:scoreCardType.QwikScore_Question_Groups__r){
            toSaveList.addAll(questionAnswerMap.get(qGroup.Id));
        }
        for(QwikScore_Question_Answer__c qAnswer : toSaveList){
            qAnswer.QwikScore_Scorecard__c = scoreCard.Id;
            qAnswer.Answer_Unique_Id__c = String.valueOf(Math.random());
        }
        //saving the question answers
        if(toSaveList.size() > 0){
            insert toSaveList;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Survey is saved successfully'));
            ScoringEngineLite.gradeScorecard(scoreCard.Id);  //ktb 7.2
            System.Debug('ktb: scoreCardType.Name= '+ scoreCardType.Name);
            // check to see if this survey should update the last_inpection date may comment out if this type does not count
            /*if( scoreCardType.Name == 'Final Walkthrough Checklist' ){
               surveyAccount.Last_Inspection__c =  datetime.now(); 
               update surveyAccount;
               System.Debug('ktb: Last_Inspection__c to be set');
            }
            */
            // check to see if this survey should update the last_inpection date
            /*if( scoreCardType.Name == 'ROR' ){
               surveyAccount.Last_Inspection__c =  datetime.now(); 
               update surveyAccount;
               System.Debug('ktb: Last_Inspection__c to be set');
            }
            */
            // update Perf_Customer_Sat__c on account record
            //if ( scoreCardType.Name == 'Customer Satisfaction Survey') {
               List<QwikScore_Scorecard__c> finishedScoreCards = [select Final_Score__c from QwikScore_Scorecard__c where QwikScore_Survey__c = :scoreCardType.Id and Survey_For__c = :surveyAccount.Id order by createdDate desc limit 10];
               Decimal totalScore = 0.0;
               for(QwikScore_Scorecard__c sCard:finishedScoreCards){
               	totalScore += sCard.Final_Score__c;
              // }
               /*
               if(finishedScoreCards!=null && finishedScoreCards.size()>0){
               		surveyAccount.Perf_Customer_Sat__c = totalScore/finishedScoreCards.size();
               }*/
              update surveyAccount;
            }
            
        }
        return new PageReference('/'+scoreCard.Id);
    }
    public PageReference noSurvey(){
        return new PageReference('/'+surveyAccount.Id);
    }
    public PageReference cancel(){
        return new PageReference('/'+surveyAccount.Id);
    }
    public void fillAnswerValues(Integer minValue,Integer maxValue){
    answerValues.put(maxValue,new List<SelectOption>());                    
        for(Integer answerValue =minValue;answerValue<=maxValue;answerValue++){
        answerValues.get(maxValue).add(new SelectOption(String.valueOf(answerValue),String.valueOf(answerValue)));
    }
    }    
}